Router
ioilmio/calculator pull request #10
Opened 2021-02-09 14:08 UTC by ioilmio

This milestone include:
- routing
- testing

2021-02-09 14:12 UTC, mikenath223 commented
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason:
- Please fix the stylelint issues before resubmitting.

2021-02-09 14:53 UTC, mikenath223 requested changes
### Hello @ioilmio 👋

**Nice work here. You did well, adding snapshots on components. 👍**

However, let's some fixes.

- Please refer to comments on the code

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-02-09 14:54 UTC, mikenath223 commented on src/logic/calculate.js
> +/* eslint-disable no-unused-expressions */
- [ ] Kindly ensure that all functions in the calculate.js file are tested with appropriate unit tests.

2021-02-09 14:55 UTC, mikenath223 commented
- [ ] In the readme the section titled: `Make you operation as usual` isn't related to this project either update it or remove it totally.

2021-02-27 04:58 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

Great job @ioilmio, and thanks for making the required changes :hammer: :wrench:.

Now you can merge, your project is approved :checkered_flag: 

## Happy Coding :tophat:

2021-03-01 14:53 UTC, merged